<a href="https://colab.research.google.com/github/hasanocal7/Kur_3/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lineer Regresyon

#Giriş - Tanım - Teori


> Lineer Regresyon, tahmine dayalı modellemede en basit ve en yayın kullanılan istatistiksel tekniklerden birdir. Gözlemlenen verilere doğrusal bir denklem uydurarak, bir bağımlı değişken y ile bir veya daha fazla bağımsız değişken  arasındaki ilişkiyi modellemeyi amaçlar.

Lineer regresyon en basit şekli, yalnızca bir bağımsı değişkenin olduğu basit lineer regresyondur. Bu durumda bir çizginin denklemi:

y = a*x+b



# Numpy ile Veri Oluşturma

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interactive
np.random.seed(42)

In [ ]:
x = 2* np.random.rand(100, 1)
y = 3 * x + 4 + np.random.rand(100, 1)

In [ ]:
def plot_func(a, b):
  plt.scatter(x, y, label = "Veri")
  plt.plot(x, a*x+b, label= "Denklem")
  plt.xlabel("x", fontsize = 16)
  plt.ylabel("y", fontsize = 16)
  plt.title(f"y = {a: .2f}* x +{b: .2f}")
  plt.legend()
  plt.show()

In [ ]:
interactive(plot_func, a=(-5, 5, 0.1), b=(-5, 5, 0.1))

interactive(children=(FloatSlider(value=0.0, description='a', max=5.0, min=-5.0), FloatSlider(value=0.0, descr…

# Numpy Verisetinde Sklearn Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [ ]:
model.fit(x, y)

LinearRegression()

a * x + b Modellenen denklem için;

*   a = model.coef_
*   b = model.intercept_

In [ ]:
model.coef_, model.intercept_

(array([[2.98323418]]), array([4.51359766]))

In [ ]:
model.predict([[1]])

array([[7.49683183]])

In [ ]:
x_input = 1
model.coef_ * x_input  + model.intercept_

array([[7.49683183]])

#Ev Fiyatları Verisetinin Yüklenmesi ve Linear Regression

In [ ]:
from sklearn.datasets import  fetch_openml
housing = fetch_openml(name = "house_prices", as_frame = True)

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [ ]:
housing.keys()

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [ ]:
X = housing.data
y = housing.target

In [ ]:
X

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave  None      Reg   
1        2          20       RL         80.0     9600   Pave  None      Reg   
2        3          60       RL         68.0    11250   Pave  None      IR1   
3        4          70       RL         60.0     9550   Pave  None      IR1   
4        5          60       RL         84.0    14260   Pave  None      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave  None      Reg   
1456  1457          20       RL         85.0    13175   Pave  None      Reg   
1457  1458          70       RL         66.0     9042   Pave  None      Reg   
1458  1459          20       RL         68.0     9717   Pave  None      Reg   
1459  1460          20       RL         75.0     9937   Pave  None      Reg   

     LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub  ...           0        0   None   None   
1            Lvl    AllPub  ...           0        0   None   None   
2            Lvl    AllPub  ...           0        0   None   None   
3            Lvl    AllPub  ...           0        0   None   None   
4            Lvl    AllPub  ...           0        0   None   None   
...          ...       ...  ...         ...      ...    ...    ...   
1455         Lvl    AllPub  ...           0        0   None   None   
1456         Lvl    AllPub  ...           0        0   None  MnPrv   
1457         Lvl    AllPub  ...           0        0   None  GdPrv   
1458         Lvl    AllPub  ...           0        0   None   None   
1459         Lvl    AllPub  ...           0        0   None   None   

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0           None       0      2    2008        WD         Normal  
1           None       0      5    2007        WD         Normal  
2           None       0      9    2008        WD         Normal  
3           None       0      2    2006        WD        Abnorml  
4           None       0     12    2008        WD         Normal  
...          ...     ...    ...     ...       ...            ...  
1455        None       0      8    2007        WD         Normal  
1456        None       0      2    2010        WD         Normal  
1457        Shed    2500      5    2010        WD         Normal  
1458        None       0      4    2010        WD         Normal  
1459        None       0      6    2008        WD         Normal  

[1460 rows x 80 columns]

In [ ]:
X.drop(["Id"], axis = 1, inplace = True)

<ipython-input-195-c0533ee2ba27>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.drop(["Id"], axis = 1, inplace = True)


In [ ]:
X.iloc[0]

MSSubClass           60
MSZoning             RL
LotFrontage        65.0
LotArea            8450
Street             Pave
                  ...  
MiscVal               0
MoSold                2
YrSold             2008
SaleType             WD
SaleCondition    Normal
Name: 0, Length: 79, dtype: object

In [ ]:
y[0]

208500

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state=42)

In [ ]:
X_train

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
615           85       RL         80.0     8800   Pave  None      Reg   
613           20       RL         70.0     8402   Pave  None      Reg   
1303          20       RL         73.0     8688   Pave  None      Reg   
486           20       RL         79.0    10289   Pave  None      Reg   
561           20       RL         77.0    10010   Pave  None      Reg   
...          ...      ...          ...      ...    ...   ...      ...   
1095          20       RL         78.0     9317   Pave  None      IR1   
1130          50       RL         65.0     7804   Pave  None      Reg   
1294          20       RL         60.0     8172   Pave  None      Reg   
860           50       RL         55.0     7642   Pave  None      Reg   
1126         120       RL         53.0     3684   Pave  None      Reg   

     LandContour Utilities LotConfig  ... ScreenPorch PoolArea PoolQC  Fence  \
615          Lvl    AllPub    Inside  ...           0        0   None  MnPrv   
613          Lvl    AllPub    Inside  ...           0        0   None   None   
1303         Lvl    AllPub    Inside  ...           0        0   None   None   
486          Lvl    AllPub    Inside  ...           0        0   None   None   
561          Lvl    AllPub    Inside  ...           0        0   None   None   
...          ...       ...       ...  ...         ...      ...    ...    ...   
1095         Lvl    AllPub    Inside  ...           0        0   None   None   
1130         Lvl    AllPub    Inside  ...           0        0   None  MnPrv   
1294         Lvl    AllPub    Inside  ...           0        0   None   None   
860          Lvl    AllPub    Corner  ...           0        0   None  GdPrv   
1126         Lvl    AllPub    Inside  ...           0        0   None   None   

     MiscFeature MiscVal  MoSold  YrSold  SaleType  SaleCondition  
615         None       0       5    2010        WD        Abnorml  
613         None       0      12    2007       New        Partial  
1303        None       0       4    2006        WD         Normal  
486         None       0       6    2007        WD         Normal  
561         None       0       4    2006        WD         Normal  
...          ...     ...     ...     ...       ...            ...  
1095        None       0       3    2007        WD         Normal  
1130        None       0      12    2009        WD         Normal  
1294        None       0       4    2006        WD         Normal  
860         None       0       6    2007        WD         Normal  
1126        None       0       6    2009        WD         Normal  

[978 rows x 79 columns]

In [ ]:
y_train

615     137500
613     147000
1303    232000
486     156000
561     170000
         ...  
1095    176432
1130    135000
1294    115000
860     189950
1126    174000
Name: SalePrice, Length: 978, dtype: int64

#Veriseti Önişleme

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 978 entries, 615 to 1126
Data columns (total 79 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MSSubClass     978 non-null    int64  
 1   MSZoning       978 non-null    object 
 2   LotFrontage    795 non-null    float64
 3   LotArea        978 non-null    int64  
 4   Street         978 non-null    object 
 5   Alley          63 non-null     object 
 6   LotShape       978 non-null    object 
 7   LandContour    978 non-null    object 
 8   Utilities      978 non-null    object 
 9   LotConfig      978 non-null    object 
 10  LandSlope      978 non-null    object 
 11  Neighborhood   978 non-null    object 
 12  Condition1     978 non-null    object 
 13  Condition2     978 non-null    object 
 14  BldgType       978 non-null    object 
 15  HouseStyle     978 non-null    object 
 16  OverallQual    978 non-null    int64  
 17  OverallCond    978 non-null    int64  
 18  YearBui

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [ ]:
categories = list(X_train.select_dtypes(include = ["object"]))

In [ ]:
numericals = list(X_train.select_dtypes(include = ["int64", "float64"]))

In [ ]:
len(categories + numericals)

79

In [ ]:
from matplotlib.cbook import simple_linear_interpolation

In [ ]:
numerical_imputer = SimpleImputer(strategy = "median")

In [ ]:
X_train[numericals] = numerical_imputer.fit_transform(X_train[numericals])

In [ ]:
X_train[numericals].isna().sum()

MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageYrBlt      0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
dtype: int64

In [ ]:
X_test[numericals] = numerical_imputer.transform(X_test[numericals])

In [ ]:
X_train

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
615         85.0       RL         80.0   8800.0   Pave  None      Reg   
613         20.0       RL         70.0   8402.0   Pave  None      Reg   
1303        20.0       RL         73.0   8688.0   Pave  None      Reg   
486         20.0       RL         79.0  10289.0   Pave  None      Reg   
561         20.0       RL         77.0  10010.0   Pave  None      Reg   
...          ...      ...          ...      ...    ...   ...      ...   
1095        20.0       RL         78.0   9317.0   Pave  None      IR1   
1130        50.0       RL         65.0   7804.0   Pave  None      Reg   
1294        20.0       RL         60.0   8172.0   Pave  None      Reg   
860         50.0       RL         55.0   7642.0   Pave  None      Reg   
1126       120.0       RL         53.0   3684.0   Pave  None      Reg   

     LandContour Utilities LotConfig  ... ScreenPorch PoolArea PoolQC  Fence  \
615          Lvl    AllPub    Inside  ...         0.0      0.0   None  MnPrv   
613          Lvl    AllPub    Inside  ...         0.0      0.0   None   None   
1303         Lvl    AllPub    Inside  ...         0.0      0.0   None   None   
486          Lvl    AllPub    Inside  ...         0.0      0.0   None   None   
561          Lvl    AllPub    Inside  ...         0.0      0.0   None   None   
...          ...       ...       ...  ...         ...      ...    ...    ...   
1095         Lvl    AllPub    Inside  ...         0.0      0.0   None   None   
1130         Lvl    AllPub    Inside  ...         0.0      0.0   None  MnPrv   
1294         Lvl    AllPub    Inside  ...         0.0      0.0   None   None   
860          Lvl    AllPub    Corner  ...         0.0      0.0   None  GdPrv   
1126         Lvl    AllPub    Inside  ...         0.0      0.0   None   None   

     MiscFeature MiscVal  MoSold  YrSold  SaleType  SaleCondition  
615         None     0.0     5.0  2010.0        WD        Abnorml  
613         None     0.0    12.0  2007.0       New        Partial  
1303        None     0.0     4.0  2006.0        WD         Normal  
486         None     0.0     6.0  2007.0        WD         Normal  
561         None     0.0     4.0  2006.0        WD         Normal  
...          ...     ...     ...     ...       ...            ...  
1095        None     0.0     3.0  2007.0        WD         Normal  
1130        None     0.0    12.0  2009.0        WD         Normal  
1294        None     0.0     4.0  2006.0        WD         Normal  
860         None     0.0     6.0  2007.0        WD         Normal  
1126        None     0.0     6.0  2009.0        WD         Normal  

[978 rows x 79 columns]

In [ ]:
encoder = OrdinalEncoder(handle_unknown="use_encoded_value",
                         unknown_value=-1)
categorical_imputer = SimpleImputer(strategy= "most_frequent")

In [ ]:
X_train[categories] = categorical_imputer.fit_transform(X_train[categories])
X_test[categories] = categorical_imputer.transform(X_test[categories])

In [ ]:
X_train[categories] = encoder.fit_transform(X_train[categories])
X_test[categories] = encoder.transform(X_test[categories])

# Modelin Kurulması

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
predictions = model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(y_test, predictions, squared = False)

37093.465395769315